// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpuHU_mK72DBc0DRhmZxJkfeqzTDkdF_4',
    appId: '1:486828439229:web:2c492023ed63ea9e6529d4',
    messagingSenderId: '486828439229',
    projectId: 'telechatapp-efc1a',
    authDomain: 'telechatapp-efc1a.firebaseapp.com',
    storageBucket: 'telechatapp-efc1a.appspot.com',
    measurementId: 'G-XHV6FFH03Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbGq5jabFel6bgexZ6_QQxMKf7rBhbsc',
    appId: '1:486828439229:android:5e8e789c30f0bf0b6529d4',
    messagingSenderId: '486828439229',
    projectId: 'telechatapp-efc1a',
    storageBucket: 'telechatapp-efc1a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpuHU_mK72DBc0DRhmZxJkfeqzTDkdF_4',
    appId: '1:486828439229:web:f36d6361401a9eb06529d4',
    messagingSenderId: '486828439229',
    projectId: 'telechatapp-efc1a',
    authDomain: 'telechatapp-efc1a.firebaseapp.com',
    storageBucket: 'telechatapp-efc1a.appspot.com',
    measurementId: 'G-06LJHCPQFQ',
  );
}
